### ISSUE TITLE
Add version bump workflow

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#235]
### Background Information

Add version bump workflow to admiralophtha (see [example](https://github.com/pharmaverse/admiral/blob/main/.github/workflows/common.yml) from admiral)

### Definition of Done

`common.yml` file updated with following workflow:
```
vbump:
  name: Version Bump 
  if: github.event_name == 'push'
  uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
  secrets:
```
